# Each of these three will be build as a ROS message
# goal
sensor_msgs/Image image
sensor_msgs/CameraInfo camera_info
---
# result
int32 number_found
geometry_msgs/PoseStamped relative_pose
---
# there is no feedback necessary
