#goal msg
Header header
uint8 location_code 
uint8 UNSET = 0
uint8 TO_MINING = 1
uint8 TO_DUMPING = 2
---
#feedback msg
Header header
geometry_msgs/Pose current
geometry_msgs/Pose goal
---
#result msg 
Header header
geometry_msgs/Pose current
geometry_msgs/Pose goal
