// do not edit! This is an autogenerated file (see regenerate_markers.py in the aruco folder)
void setBoardData(std::vector<std::vector<cv::Point3f> > &boardCorners, std::vector<int> &boardIds)
{
	std::vector<cv::Point3f> markerPoints;
	markerPoints = 
	{
	cv::Point3f(-0.73, 0.02, 0),
	cv::Point3f(-0.495, 0.02, 0),
	cv::Point3f(-0.495, 0.255, 0),
	cv::Point3f(-0.73, 0.255, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(1);

	markerPoints = 
	{
	cv::Point3f(0.495, 0.02, 0),
	cv::Point3f(0.73, 0.02, 0),
	cv::Point3f(0.73, 0.255, 0),
	cv::Point3f(0.495, 0.255, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(2);

	markerPoints = 
	{
	cv::Point3f(-0.467, 0.178, 0),
	cv::Point3f(-0.415, 0.178, 0),
	cv::Point3f(-0.415, 0.23, 0),
	cv::Point3f(-0.467, 0.23, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(3);

	markerPoints = 
	{
	cv::Point3f(-0.399, 0.178, 0),
	cv::Point3f(-0.347, 0.178, 0),
	cv::Point3f(-0.347, 0.23, 0),
	cv::Point3f(-0.399, 0.23, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(4);

	markerPoints = 
	{
	cv::Point3f(-0.331, 0.178, 0),
	cv::Point3f(-0.279, 0.178, 0),
	cv::Point3f(-0.279, 0.23, 0),
	cv::Point3f(-0.331, 0.23, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(5);

	markerPoints = 
	{
	cv::Point3f(-0.263, 0.178, 0),
	cv::Point3f(-0.211, 0.178, 0),
	cv::Point3f(-0.211, 0.23, 0),
	cv::Point3f(-0.263, 0.23, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(6);

	markerPoints = 
	{
	cv::Point3f(-0.195, 0.178, 0),
	cv::Point3f(-0.143, 0.178, 0),
	cv::Point3f(-0.143, 0.23, 0),
	cv::Point3f(-0.195, 0.23, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(7);

	markerPoints = 
	{
	cv::Point3f(-0.127, 0.178, 0),
	cv::Point3f(-0.075, 0.178, 0),
	cv::Point3f(-0.075, 0.23, 0),
	cv::Point3f(-0.127, 0.23, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(8);

	markerPoints = 
	{
	cv::Point3f(-0.059, 0.178, 0),
	cv::Point3f(-0.007, 0.178, 0),
	cv::Point3f(-0.007, 0.23, 0),
	cv::Point3f(-0.059, 0.23, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(9);

	markerPoints = 
	{
	cv::Point3f(0.009, 0.178, 0),
	cv::Point3f(0.061, 0.178, 0),
	cv::Point3f(0.061, 0.23, 0),
	cv::Point3f(0.009, 0.23, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(10);

	markerPoints = 
	{
	cv::Point3f(0.077, 0.178, 0),
	cv::Point3f(0.129, 0.178, 0),
	cv::Point3f(0.129, 0.23, 0),
	cv::Point3f(0.077, 0.23, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(11);

	markerPoints = 
	{
	cv::Point3f(0.145, 0.178, 0),
	cv::Point3f(0.197, 0.178, 0),
	cv::Point3f(0.197, 0.23, 0),
	cv::Point3f(0.145, 0.23, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(12);

	markerPoints = 
	{
	cv::Point3f(0.213, 0.178, 0),
	cv::Point3f(0.265, 0.178, 0),
	cv::Point3f(0.265, 0.23, 0),
	cv::Point3f(0.213, 0.23, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(13);

	markerPoints = 
	{
	cv::Point3f(0.281, 0.178, 0),
	cv::Point3f(0.333, 0.178, 0),
	cv::Point3f(0.333, 0.23, 0),
	cv::Point3f(0.281, 0.23, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(14);

	markerPoints = 
	{
	cv::Point3f(0.349, 0.178, 0),
	cv::Point3f(0.401, 0.178, 0),
	cv::Point3f(0.401, 0.23, 0),
	cv::Point3f(0.349, 0.23, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(15);

	markerPoints = 
	{
	cv::Point3f(0.417, 0.178, 0),
	cv::Point3f(0.469, 0.178, 0),
	cv::Point3f(0.469, 0.23, 0),
	cv::Point3f(0.417, 0.23, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(16);

	markerPoints = 
	{
	cv::Point3f(-0.46, 0.015, 0),
	cv::Point3f(-0.335, 0.015, 0),
	cv::Point3f(-0.335, 0.14, 0),
	cv::Point3f(-0.46, 0.14, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(17);

	markerPoints = 
	{
	cv::Point3f(-0.305, 0.015, 0),
	cv::Point3f(-0.18, 0.015, 0),
	cv::Point3f(-0.18, 0.14, 0),
	cv::Point3f(-0.305, 0.14, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(18);

	markerPoints = 
	{
	cv::Point3f(-0.15, 0.015, 0),
	cv::Point3f(-0.025, 0.015, 0),
	cv::Point3f(-0.025, 0.14, 0),
	cv::Point3f(-0.15, 0.14, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(19);

	markerPoints = 
	{
	cv::Point3f(0.005, 0.015, 0),
	cv::Point3f(0.13, 0.015, 0),
	cv::Point3f(0.13, 0.14, 0),
	cv::Point3f(0.005, 0.14, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(20);

	markerPoints = 
	{
	cv::Point3f(0.16, 0.015, 0),
	cv::Point3f(0.285, 0.015, 0),
	cv::Point3f(0.285, 0.14, 0),
	cv::Point3f(0.16, 0.14, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(21);

	markerPoints = 
	{
	cv::Point3f(0.315, 0.015, 0),
	cv::Point3f(0.44, 0.015, 0),
	cv::Point3f(0.44, 0.14, 0),
	cv::Point3f(0.315, 0.14, 0)
	};
	boardCorners.push_back(markerPoints);
	boardIds.push_back(22);

}
