#! /bin/bash
echo ""
echo "------------------------------------ Building ------------------------------------"
echo ""


ARCH=$(uname -m)
CMAKE_OPTIONS="-DARCH_DIR=$ARCH"

catkin_make --cmake-args $CMAKE_OPTIONS

if [ $? -eq 0 ]; then
    echo ""
	echo "--------------------------------- Building Tests ---------------------------------"
	echo ""
	
	catkin_make tests --cmake-args $CMAKE_OPTIONS
	
	if [ $? -eq 0 ]; then
		echo ""
		echo "--------------------------------- Build Succeeded --------------------------------"
		echo ""
	else
		echo ""
		echo "------------------------------- Building Tests Failed ----------------------------"
		echo ""
	fi
else
	echo ""
	echo "---------------------------------- Build Failed ----------------------------------"
	echo ""
fi
