#!/bin/bash

echo ""
echo "------------------------------------ Building ------------------------------------"
echo ""

catkin_make

if [ $? -eq 0 ]; then
    echo ""
	echo "--------------------------------- Building Tests ---------------------------------"
	echo ""
	
	catkin_make tests
	
	if [ $? -eq 0 ]; then
		echo ""
		echo "--------------------------------- Build Succeeded --------------------------------"
		echo ""
	else
		echo ""
		echo "------------------------------- Building Tests Failed ----------------------------"
		echo ""
	fi
else
	echo ""
	echo "---------------------------------- Build Failed ----------------------------------"
	echo ""
fi
