#!/bin/bash

echo ""
echo "------------------------------------ Utilites ------------------------------------"
echo ""
rosrun tfr_utilities tfr_utilities-test
echo ""
echo ""
echo "------------------------------------- Control -------------------------------------"
echo ""
rosrun tfr_control tfr_control-test
